#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \Console\Setup(null));
$application->add(new \Console\slashCommands(null));

$application->run();